//! `codex app-server` (JSON-RPC v2) messages → normalized events.
//!
//! Shapes follow the protocol generated by `codex app-server generate-ts`
//! (codex-cli 0.156.1) and the traffic recorded in
//! `fixtures/codex/appserver/*-real.json`. Observed behaviour this relies on:
//!
//! * one managed session = one root thread; its id is the session id;
//! * a subagent is a separate thread: `spawnAgent` collab calls name it in
//!   `receiverThreadIds`, and its notifications carry its own `threadId`
//!   (no `thread/started` is sent for it);
//! * `thread/tokenUsage/updated.total` is a running total per thread;
//! * approvals are server→client requests answered with a decision.

use crate::tools::{self, PatchOp};
use crate::PROVIDER_ID;
use ao_core::event::*;
use ao_core::ids::{AgentId, PermissionRequestId, SessionId, ToolCallId};
use ao_core::provider::PermissionDecision;
use serde_json::{json, Value};
use std::collections::{HashMap, HashSet};

fn s<'a>(v: &'a Value, key: &str) -> Option<&'a str> {
    v.get(key).and_then(Value::as_str).filter(|x| !x.is_empty())
}

fn u(v: &Value, key: &str) -> Option<u64> {
    v.get(key).and_then(Value::as_u64)
}

fn clip(text: &str, max: usize) -> String {
    if text.chars().count() <= max {
        text.to_owned()
    } else {
        format!("{}…", text.chars().take(max).collect::<String>())
    }
}

/// Command text for display: the parsed action when Codex could parse exactly
/// one, otherwise the raw command (which includes the shell wrapper).
pub fn display_command(item: &Value) -> Option<String> {
    let actions = item.get("commandActions").and_then(Value::as_array);
    if let Some([single]) = actions.map(Vec::as_slice) {
        if let Some(cmd) = s(single, "command") {
            return Some(cmd.to_owned());
        }
    }
    s(item, "command").map(str::to_owned)
}

/// `codexErrorInfo` is either a string (`"usageLimitExceeded"`) or an
/// object with one key (`{"httpConnectionFailed": {...}}`).
fn error_kind(info: &Value) -> Option<String> {
    match info {
        Value::String(s) => Some(s.clone()),
        Value::Object(map) => map.keys().next().cloned(),
        _ => None,
    }
}

fn transient(kind: Option<&str>) -> bool {
    matches!(
        kind,
        Some(
            "rateLimitExceeded"
                | "serverOverloaded"
                | "internalServerError"
                | "httpConnectionFailed"
                | "responseStreamConnectionFailed"
                | "responseStreamDisconnected"
                | "responseTooManyFailedAttempts"
        )
    )
}

fn error_message(error: &Value) -> String {
    let message = s(error, "message").unwrap_or("Codex reported an error");
    match s(error, "additionalDetails") {
        Some(details) => format!("{message} ({})", clip(details, 300)),
        None => message.to_owned(),
    }
}

#[derive(Debug, Clone, Copy, Default)]
struct Totals {
    input: u64,
    cached: u64,
    output: u64,
    reasoning: u64,
    total: u64,
}

/// What an approval request is about, kept until it is answered.
#[derive(Debug, Clone, PartialEq)]
pub enum ApprovalKind {
    Command,
    FileChange,
    /// Extra permissions (network / file system). The requested profile is
    /// granted back as-is when approved.
    Permissions(Value),
}

impl ApprovalKind {
    /// The JSON-RPC result for a decision (shapes from
    /// `*RequestApprovalResponse` in the generated protocol).
    pub fn response(&self, decision: &PermissionDecision) -> Value {
        match (self, decision) {
            (ApprovalKind::Permissions(requested), PermissionDecision::Approve { for_session }) => {
                let mut granted = serde_json::Map::new();
                for key in ["network", "fileSystem"] {
                    if let Some(v) = requested.get(key).filter(|v| !v.is_null()) {
                        granted.insert(key.into(), v.clone());
                    }
                }
                json!({ "permissions": granted, "scope": if *for_session { "session" } else { "turn" } })
            }
            (ApprovalKind::Permissions(_), PermissionDecision::Reject { .. }) => {
                json!({ "permissions": {}, "scope": "turn" })
            }
            (_, PermissionDecision::Approve { for_session: true }) => {
                json!({ "decision": "acceptForSession" })
            }
            (_, PermissionDecision::Approve { .. }) => json!({ "decision": "accept" }),
            (_, PermissionDecision::Reject { .. }) => json!({ "decision": "decline" }),
        }
    }

    /// The answer when nobody decided in time.
    pub fn timeout_response(&self) -> Value {
        self.response(&PermissionDecision::Reject { message: None })
    }
}

/// An approval the server is waiting for.
#[derive(Debug, Clone)]
pub struct Approval {
    pub request_id: String,
    pub kind: ApprovalKind,
    /// Thread that asked (root or a subagent).
    pub thread: String,
    pub event: AgentEvent,
}

/// Stateful mapper for one managed session (one root thread).
#[derive(Debug)]
pub struct Mapper {
    root: String,
    children: HashSet<String>,
    usage: HashMap<String, Totals>,
    context_window: Option<u64>,
    file_changes: HashMap<String, Vec<(PatchOp, String)>>,
    commands: HashMap<String, String>,
    /// Session folder, to show file paths relative to it.
    cwd: Option<String>,
    /// Turn in progress on the root thread (for `turn/steer` / interrupt).
    pub active_turn: Option<String>,
}

impl Mapper {
    pub fn new(root_thread: impl Into<String>) -> Self {
        Self {
            root: root_thread.into(),
            children: HashSet::new(),
            usage: HashMap::new(),
            context_window: None,
            file_changes: HashMap::new(),
            commands: HashMap::new(),
            cwd: None,
            active_turn: None,
        }
    }

    pub fn with_cwd(mut self, cwd: impl Into<String>) -> Self {
        self.cwd = Some(cwd.into());
        self
    }

    /// Changes with paths shown relative to the session folder.
    fn relative_changes(&self, changes: &[(PatchOp, String)]) -> Vec<(PatchOp, String)> {
        changes
            .iter()
            .map(|(op, path)| (*op, tools::relative(path, self.cwd.as_deref())))
            .collect()
    }

    pub fn root(&self) -> &str {
        &self.root
    }

    /// Event for `thread` (the main agent for the root thread, otherwise the
    /// subagent with that thread id).
    pub fn event(&self, thread: &str, at: i64, kind: EventKind) -> AgentEvent {
        let e = AgentEvent::for_session(
            PROVIDER_ID,
            SessionId::new(&self.root),
            EventSource::Protocol,
            kind,
        )
        .at(at);
        if thread.is_empty() || thread == self.root {
            e
        } else {
            e.with_agent(AgentId::new(thread), None)
        }
    }

    /// First sight of a subagent thread that no spawn call announced yet.
    fn ensure_child(&mut self, thread: &str, at: i64, out: &mut Vec<AgentEvent>) {
        if !thread.is_empty() && thread != self.root && self.children.insert(thread.to_owned()) {
            out.push(self.event(
                thread,
                at,
                EventKind::SubagentStarted(SubagentInfo::default()),
            ));
        }
    }

    /// Maps one server notification. `at` is `emittedAtMs` when present.
    pub fn notification(&mut self, method: &str, params: &Value, at: i64) -> Vec<AgentEvent> {
        let thread = s(params, "threadId").unwrap_or_default().to_owned();
        let mut out = Vec::new();
        match method {
            "turn/started" => {
                self.ensure_child(&thread, at, &mut out);
                if thread == self.root {
                    self.active_turn = params
                        .pointer("/turn/id")
                        .and_then(Value::as_str)
                        .map(str::to_owned);
                }
                out.push(self.event(
                    &thread,
                    at,
                    EventKind::AgentThinking(TextNote {
                        text: Some("Working".into()),
                    }),
                ));
            }
            "turn/completed" => {
                self.ensure_child(&thread, at, &mut out);
                if thread == self.root {
                    self.active_turn = None;
                }
                let turn = params.get("turn").cloned().unwrap_or(Value::Null);
                match s(&turn, "status") {
                    Some("failed") => {
                        let error = turn.get("error").cloned().unwrap_or(Value::Null);
                        let kind = error.get("codexErrorInfo").and_then(error_kind);
                        out.push(self.event(
                            &thread,
                            at,
                            EventKind::AgentError(AgentError {
                                message: error_message(&error),
                                recoverable: transient(kind.as_deref()),
                                error_type: kind,
                            }),
                        ));
                    }
                    Some("interrupted") => out.push(self.event(
                        &thread,
                        at,
                        EventKind::AgentIdle(TextNote {
                            text: Some("Turn interrupted".into()),
                        }),
                    )),
                    _ => out.push(self.event(
                        &thread,
                        at,
                        EventKind::AgentIdle(TextNote {
                            text: Some("Turn finished — waiting for your next prompt".into()),
                        }),
                    )),
                }
            }
            "error" => {
                let error = params.get("error").cloned().unwrap_or(Value::Null);
                let will_retry = params
                    .get("willRetry")
                    .and_then(Value::as_bool)
                    .unwrap_or(false);
                out.push(self.event(
                    &thread,
                    at,
                    EventKind::AgentError(AgentError {
                        message: error_message(&error),
                        error_type: error.get("codexErrorInfo").and_then(error_kind),
                        recoverable: will_retry,
                    }),
                ));
            }
            "thread/status/changed" => {
                if params.pointer("/status/type").and_then(Value::as_str) == Some("systemError") {
                    out.push(self.event(
                        &thread,
                        at,
                        EventKind::AgentError(AgentError {
                            message: "Codex reported a system error on this thread".into(),
                            error_type: Some("systemError".into()),
                            recoverable: false,
                        }),
                    ));
                }
            }
            "thread/tokenUsage/updated" => {
                let usage = params.get("tokenUsage").cloned().unwrap_or(Value::Null);
                let total = usage.get("total").cloned().unwrap_or(Value::Null);
                self.usage.insert(
                    thread.clone(),
                    Totals {
                        input: u(&total, "inputTokens").unwrap_or(0),
                        cached: u(&total, "cachedInputTokens").unwrap_or(0),
                        output: u(&total, "outputTokens").unwrap_or(0),
                        reasoning: u(&total, "reasoningOutputTokens").unwrap_or(0),
                        total: u(&total, "totalTokens").unwrap_or(0),
                    },
                );
                if let Some(window) = u(&usage, "modelContextWindow") {
                    self.context_window = Some(self.context_window.unwrap_or(0).max(window));
                }
                let sum = self.usage.values().fold(Totals::default(), |a, t| Totals {
                    input: a.input + t.input,
                    cached: a.cached + t.cached,
                    output: a.output + t.output,
                    reasoning: a.reasoning + t.reasoning,
                    total: a.total + t.total,
                });
                // Session-wide totals (all threads) on the main agent. Codex
                // reports no cost.
                out.push(self.event(
                    &self.root.clone(),
                    at,
                    EventKind::UsageUpdated(UsageSnapshot {
                        input_tokens: Some(sum.input),
                        output_tokens: Some(sum.output),
                        cached_input_tokens: Some(sum.cached),
                        reasoning_tokens: Some(sum.reasoning),
                        total_tokens: Some(sum.total),
                        context_window: self.context_window,
                        cost_usd: None,
                        ..Default::default()
                    }),
                ));
            }
            "thread/closed" if thread != self.root && self.children.remove(&thread) => {
                out.push(self.event(
                    &thread,
                    at,
                    EventKind::SubagentEnded(SubagentInfo {
                        reason: Some("closed".into()),
                        ..Default::default()
                    }),
                ));
            }
            "model/rerouted" if thread == self.root => {
                out.push(self.event(
                    &thread,
                    at,
                    EventKind::SessionUpdated(SessionInfo {
                        model: s(params, "toModel").map(str::to_owned),
                        ..Default::default()
                    }),
                ));
            }
            "thread/name/updated" if thread == self.root => {
                if let Some(name) = s(params, "threadName") {
                    out.push(self.event(
                        &thread,
                        at,
                        EventKind::SessionUpdated(SessionInfo {
                            title: Some(name.to_owned()),
                            ..Default::default()
                        }),
                    ));
                }
            }
            "item/started" | "item/completed" => {
                let item = params.get("item").cloned().unwrap_or(Value::Null);
                let started = method == "item/started";
                self.item(&thread, &item, started, at, &mut out);
            }
            // Deltas, hooks, diffs, warnings, rate limits, account and
            // realtime notifications carry nothing the office shows.
            _ => {}
        }
        out
    }

    fn item(
        &mut self,
        thread: &str,
        item: &Value,
        started: bool,
        at: i64,
        out: &mut Vec<AgentEvent>,
    ) {
        let Some(kind) = s(item, "type") else { return };
        let id = s(item, "id").map(str::to_owned);
        let status = s(item, "status");
        let tool = |name: &str, category: ToolCategory, title: Option<String>| ToolStarted {
            tool_call_id: id.clone().map(ToolCallId),
            tool_name: name.to_owned(),
            category,
            title,
        };
        let finished = |name: &str,
                        category: ToolCategory,
                        duration: Option<u64>,
                        detail: Option<String>| ToolFinished {
            tool_call_id: id.clone().map(ToolCallId),
            tool_name: name.to_owned(),
            category,
            duration_ms: duration,
            detail,
        };
        if kind != "collabAgentToolCall" {
            self.ensure_child(thread, at, out);
        }
        match (kind, started) {
            ("userMessage", false) => {
                let text: Vec<&str> = item
                    .get("content")
                    .and_then(Value::as_array)
                    .map(|c| {
                        c.iter()
                            .filter(|p| s(p, "type") == Some("text"))
                            .filter_map(|p| s(p, "text"))
                            .collect()
                    })
                    .unwrap_or_default();
                out.push(self.event(
                    thread,
                    at,
                    EventKind::PromptSubmitted(PromptSubmitted {
                        text: Some(text.join("\n")).filter(|t| !t.is_empty()),
                    }),
                ));
            }
            ("agentMessage", false) => {
                if let Some(text) = s(item, "text") {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::AgentMessage(TextNote {
                            text: Some(clip(text, 2000)),
                        }),
                    ));
                }
            }
            ("commandExecution", true) => {
                let command = display_command(item).unwrap_or_default();
                if let Some(id) = &id {
                    self.commands.insert(id.clone(), command.clone());
                }
                out.push(self.event(
                    thread,
                    at,
                    EventKind::ToolStarted(tool(
                        "commandExecution",
                        ToolCategory::Execute,
                        Some(tools::first_line(&command, 120)),
                    )),
                ));
                out.push(self.event(
                    thread,
                    at,
                    EventKind::CommandStarted(CommandStarted {
                        command_id: id.clone(),
                        command,
                        cwd: s(item, "cwd").map(str::to_owned),
                    }),
                ));
            }
            ("commandExecution", false) => {
                let command = display_command(item);
                let exit = item
                    .get("exitCode")
                    .and_then(Value::as_i64)
                    .map(|c| c as i32);
                let duration = u(item, "durationMs");
                let failed =
                    matches!(status, Some("failed" | "declined")) || exit.is_some_and(|c| c != 0);
                let error = match status {
                    Some("declined") => Some("Declined".to_owned()),
                    _ if failed => s(item, "aggregatedOutput")
                        .map(|o| clip(o.lines().last().unwrap_or_default(), 200)),
                    _ => None,
                };
                let result = CommandFinished {
                    command_id: id.clone(),
                    command,
                    exit_code: exit,
                    duration_ms: duration,
                    error: error.clone(),
                };
                if failed {
                    out.push(self.event(thread, at, EventKind::CommandFailed(result)));
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolFailed(finished(
                            "commandExecution",
                            ToolCategory::Execute,
                            duration,
                            error,
                        )),
                    ));
                } else {
                    out.push(self.event(thread, at, EventKind::CommandCompleted(result)));
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            "commandExecution",
                            ToolCategory::Execute,
                            duration,
                            None,
                        )),
                    ));
                }
                if let Some(id) = &id {
                    self.commands.remove(id);
                }
            }
            ("fileChange", _) => {
                let changes: Vec<(PatchOp, String)> = item
                    .get("changes")
                    .and_then(Value::as_array)
                    .map(|list| {
                        list.iter()
                            .filter_map(|c| {
                                let path = s(c, "path")?.to_owned();
                                let op = match c.pointer("/kind/type").and_then(Value::as_str) {
                                    Some("add") => PatchOp::Add,
                                    Some("delete") => PatchOp::Delete,
                                    _ => PatchOp::Update,
                                };
                                let path = c
                                    .pointer("/kind/move_path")
                                    .and_then(Value::as_str)
                                    .map(str::to_owned)
                                    .unwrap_or(path);
                                Some((op, path))
                            })
                            .collect()
                    })
                    .unwrap_or_default();
                if started {
                    if let Some(id) = &id {
                        self.file_changes.insert(id.clone(), changes.clone());
                    }
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolStarted(tool(
                            "fileChange",
                            ToolCategory::Edit,
                            Some(format!(
                                "Edit: {}",
                                tools::describe_changes(&self.relative_changes(&changes))
                            )),
                        )),
                    ));
                    return;
                }
                if let Some(id) = &id {
                    self.file_changes.remove(id);
                }
                if status == Some("completed") {
                    for (op, path) in changes {
                        let touched = FileTouched {
                            path,
                            tool_call_id: id.clone().map(ToolCallId),
                        };
                        out.push(self.event(
                            thread,
                            at,
                            match op {
                                PatchOp::Add => EventKind::FileCreated(touched),
                                PatchOp::Update => EventKind::FileModified(touched),
                                PatchOp::Delete => EventKind::FileDeleted(touched),
                            },
                        ));
                    }
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            "fileChange",
                            ToolCategory::Edit,
                            None,
                            None,
                        )),
                    ));
                } else {
                    let detail = if status == Some("declined") {
                        "Declined"
                    } else {
                        "Patch failed"
                    };
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolFailed(finished(
                            "fileChange",
                            ToolCategory::Edit,
                            None,
                            Some(detail.into()),
                        )),
                    ));
                }
            }
            ("mcpToolCall", _) => {
                let name = format!(
                    "mcp__{}__{}",
                    s(item, "server").unwrap_or_default(),
                    s(item, "tool").unwrap_or_default()
                );
                if started {
                    let title = tools::mcp_title(&name);
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolStarted(tool(&name, ToolCategory::Mcp, Some(title))),
                    ));
                } else if status == Some("failed") {
                    let detail = item
                        .pointer("/error/message")
                        .and_then(Value::as_str)
                        .map(|m| clip(m, 300));
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolFailed(finished(
                            &name,
                            ToolCategory::Mcp,
                            u(item, "durationMs"),
                            detail,
                        )),
                    ));
                } else {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            &name,
                            ToolCategory::Mcp,
                            u(item, "durationMs"),
                            None,
                        )),
                    ));
                }
            }
            ("dynamicToolCall", _) => {
                let name = s(item, "tool").unwrap_or("tool").to_owned();
                if started {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolStarted(tool(
                            &name,
                            ToolCategory::Other,
                            Some(name.clone()),
                        )),
                    ));
                } else if item.get("success").and_then(Value::as_bool) == Some(false) {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolFailed(finished(
                            &name,
                            ToolCategory::Other,
                            u(item, "durationMs"),
                            None,
                        )),
                    ));
                } else {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            &name,
                            ToolCategory::Other,
                            u(item, "durationMs"),
                            None,
                        )),
                    ));
                }
            }
            ("webSearch", _) => {
                if started {
                    let query = s(item, "query")
                        .or_else(|| item.pointer("/action/query").and_then(Value::as_str));
                    let title =
                        query.map(|q| format!("Search the web: {}", tools::first_line(q, 60)));
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolStarted(tool("webSearch", ToolCategory::Fetch, title)),
                    ));
                } else {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            "webSearch",
                            ToolCategory::Fetch,
                            None,
                            None,
                        )),
                    ));
                }
            }
            ("imageView", _) => {
                if started {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolStarted(tool(
                            "imageView",
                            ToolCategory::Read,
                            Some("View an image".into()),
                        )),
                    ));
                } else {
                    out.push(self.event(
                        thread,
                        at,
                        EventKind::ToolCompleted(finished(
                            "imageView",
                            ToolCategory::Read,
                            None,
                            None,
                        )),
                    ));
                }
            }
            ("contextCompaction", false) => {
                out.push(self.event(thread, at, EventKind::ContextCompacted(TextNote::default())));
            }
            ("collabAgentToolCall", _) => self.collab(thread, item, started, at, out),
            _ => {}
        }
    }

    fn collab(
        &mut self,
        thread: &str,
        item: &Value,
        started: bool,
        at: i64,
        out: &mut Vec<AgentEvent>,
    ) {
        let id = s(item, "id").map(str::to_owned);
        let collab_tool = s(item, "tool").unwrap_or("agents");
        let prompt = s(item, "prompt");
        if started {
            let title = match (collab_tool, prompt) {
                ("spawnAgent", Some(p)) => format!("Spawn agent: {}", tools::first_line(p, 80)),
                ("spawnAgent", None) => "Spawn agent".to_owned(),
                (other, _) => format!("Agents: {other}"),
            };
            out.push(self.event(
                thread,
                at,
                EventKind::ToolStarted(ToolStarted {
                    tool_call_id: id.map(ToolCallId),
                    tool_name: "collabAgentToolCall".into(),
                    category: ToolCategory::Subagent,
                    title: Some(title),
                }),
            ));
            return;
        }
        let receivers: Vec<String> = item
            .get("receiverThreadIds")
            .and_then(Value::as_array)
            .map(|r| {
                r.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default();
        let status = s(item, "status");
        if status == Some("completed") {
            match collab_tool {
                "spawnAgent" => {
                    for child in &receivers {
                        let info = SubagentInfo {
                            agent_type: None,
                            description: prompt.map(|p| clip(p, 200)),
                            reason: None,
                        };
                        let kind = if self.children.insert(child.clone()) {
                            EventKind::SubagentStarted(info)
                        } else {
                            EventKind::SubagentUpdated(info)
                        };
                        out.push(self.event(child, at, kind));
                    }
                }
                "closeAgent" => {
                    for child in &receivers {
                        if self.children.remove(child) {
                            out.push(self.event(
                                child,
                                at,
                                EventKind::SubagentEnded(SubagentInfo {
                                    reason: Some("closed".into()),
                                    ..Default::default()
                                }),
                            ));
                        }
                    }
                }
                _ => {}
            }
        }
        let finished = ToolFinished {
            tool_call_id: id.map(ToolCallId),
            tool_name: "collabAgentToolCall".into(),
            category: ToolCategory::Subagent,
            duration_ms: None,
            detail: None,
        };
        out.push(self.event(
            thread,
            at,
            if matches!(status, Some("failed" | "interrupted")) {
                EventKind::ToolFailed(finished)
            } else {
                EventKind::ToolCompleted(finished)
            },
        ));
    }

    /// Maps an approval request (server → client). `None` for requests that
    /// are not approvals.
    pub fn approval(
        &mut self,
        method: &str,
        rpc_id: &Value,
        params: &Value,
        at: i64,
    ) -> Option<Approval> {
        let thread = s(params, "threadId").unwrap_or_default().to_owned();
        let item_id = s(params, "itemId").unwrap_or_default();
        let reason = s(params, "reason");
        let (kind, tool_name, description) = match method {
            "item/commandExecution/requestApproval" => {
                let command = self
                    .commands
                    .get(item_id)
                    .cloned()
                    .or_else(|| display_command(params))
                    .unwrap_or_default();
                let description = if s(params, "kind") == Some("writeStdin") {
                    format!("Send input to: {}", tools::first_line(&command, 140))
                } else {
                    format!("Run: {}", tools::first_line(&command, 160))
                };
                (ApprovalKind::Command, "commandExecution", description)
            }
            "item/fileChange/requestApproval" => {
                let description = match s(params, "grantRoot") {
                    Some(root) => format!("Allow writing under {root}"),
                    None => format!(
                        "Apply changes: {}",
                        tools::describe_changes(
                            &self.relative_changes(
                                self.file_changes
                                    .get(item_id)
                                    .map(Vec::as_slice)
                                    .unwrap_or_default()
                            )
                        )
                    ),
                };
                (ApprovalKind::FileChange, "fileChange", description)
            }
            "item/permissions/requestApproval" => {
                let requested = params.get("permissions").cloned().unwrap_or(Value::Null);
                let mut what = Vec::new();
                if requested.get("network").is_some_and(|v| !v.is_null()) {
                    what.push("network access");
                }
                if requested.get("fileSystem").is_some_and(|v| !v.is_null()) {
                    what.push("file system access");
                }
                let description = format!(
                    "Grant extra permissions: {}",
                    if what.is_empty() {
                        "unspecified".to_owned()
                    } else {
                        what.join(" and ")
                    }
                );
                (
                    ApprovalKind::Permissions(requested),
                    "permissions",
                    description,
                )
            }
            _ => return None,
        };
        let description = match reason {
            Some(r) => format!("{description} — {}", clip(r, 200)),
            None => description,
        };
        let request_id = format!("codex-{}", rpc_id_string(rpc_id));
        let event = self.event(
            &thread,
            at,
            EventKind::PermissionRequested(PermissionRequested {
                request_id: PermissionRequestId(request_id.clone()),
                tool_name: Some(tool_name.into()),
                description,
                can_resolve: true,
                options: Vec::new(),
            }),
        );
        Some(Approval {
            request_id,
            kind,
            thread,
            event,
        })
    }
}

/// JSON-RPC ids are numbers or strings; both become `"<id>"`.
pub fn rpc_id_string(id: &Value) -> String {
    match id {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn approval_responses_follow_the_protocol() {
        let approve = PermissionDecision::Approve { for_session: false };
        let session = PermissionDecision::Approve { for_session: true };
        let reject = PermissionDecision::Reject { message: None };
        assert_eq!(
            ApprovalKind::Command.response(&approve),
            json!({"decision": "accept"})
        );
        assert_eq!(
            ApprovalKind::FileChange.response(&session),
            json!({"decision": "acceptForSession"})
        );
        assert_eq!(
            ApprovalKind::Command.response(&reject),
            json!({"decision": "decline"})
        );
        let requested = json!({"network": {"enabled": true}, "fileSystem": null});
        let perms = ApprovalKind::Permissions(requested);
        assert_eq!(
            perms.response(&approve),
            json!({"permissions": {"network": {"enabled": true}}, "scope": "turn"})
        );
        assert_eq!(
            perms.timeout_response(),
            json!({"permissions": {}, "scope": "turn"})
        );
    }

    #[test]
    fn unknown_threads_become_subagents_once() {
        let mut m = Mapper::new("root");
        let events = m.notification(
            "turn/started",
            &json!({"threadId": "child", "turn": {"id": "t"}}),
            1,
        );
        assert_eq!(events.len(), 2);
        assert!(matches!(events[0].kind, EventKind::SubagentStarted(_)));
        assert_eq!(events[1].agent_id.0, "child");
        assert_eq!(
            m.notification(
                "turn/started",
                &json!({"threadId": "child", "turn": {"id": "t2"}}),
                2
            )
            .len(),
            1
        );
        assert_eq!(m.active_turn, None, "only the root turn is tracked");
        m.notification(
            "turn/started",
            &json!({"threadId": "root", "turn": {"id": "t3"}}),
            3,
        );
        assert_eq!(m.active_turn.as_deref(), Some("t3"));
    }
}
