// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activity = "IDLE" | "THINKING" | "READING" | "CODING" | "RUNNING_COMMAND" | "TESTING" | "WAITING_PERMISSION" | "WAITING_INPUT" | "ERROR" | "DONE";
