// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activity } from "./Activity";
import type { AgentId } from "./AgentId";
import type { PermissionRequested } from "./PermissionRequested";
import type { ProviderId } from "./ProviderId";
import type { RunningTool } from "./RunningTool";
import type { SessionId } from "./SessionId";

export type AgentState = { key: string, sessionKey: string, provider: ProviderId, sessionId: SessionId, agentId: AgentId, isMain: boolean, parentKey?: string, name: string, agentType?: string, activity: Activity, activitySince: number, currentAction?: string, runningTools: Array<RunningTool>, pendingPermission?: PermissionRequested, lastMessage?: string, lastError?: string, toolCalls: number, ended: boolean, endedAt?: number, };
