// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent id inside a session. The main agent uses the session id; subagents use the provider's id.
 */
export type AgentId = string;
