// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendStatus = { ok: boolean, uptimeMs: number, eventsIngested: number, eventsDropped: number, duplicatesDropped: number, activeSessions: number, uiSubscribed: boolean, maxOutputChars: number, storePrompts: boolean, };
