// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ImplementedFeatures } from "./ImplementedFeatures";

/**
 * Capabilities for both integration modes plus human-readable notes.
 */
export type CapabilityProfile = { managed: Capabilities, external: Capabilities, 
/**
 * Whether the adapter itself is implemented in this build. Capabilities
 * describe what the provider offers; `implemented` says what Agent Office
 * can already use. The UI enables actions only when both are true.
 */
implemented: ImplementedFeatures, notes: Array<string>, };
