// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Support } from "./Support";

/**
 * Capability set for one integration mode (managed or external sessions).
 */
export type Capabilities = { launch: Support, attach: Support, listSessions: Support, stop: Support, sendPrompt: Support, structuredEvents: Support, toolEvents: Support, fileEvents: Support, commandEvents: Support, permissions: Support, subagents: Support, usage: Support, cost: Support, model: Support, contextCompaction: Support, resume: Support, };
