// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a file differs, as Git reports it.
 */
export type ChangeKind = "modified" | "typeChanged" | "added" | "deleted" | "renamed" | "copied" | "untracked" | "conflicted";
