// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandFinished = { commandId?: string, command?: string, exitCode?: number, durationMs?: number, error?: string, };
