// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitInfo = { sha: string, shortSha: string, author: string, 
/**
 * Commit time (committer date), milliseconds since the epoch.
 */
time: number, summary: string, };
