// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendStatus } from "./BackendStatus";
import type { DatabaseStatus } from "./DatabaseStatus";
import type { InstallationInfo } from "./InstallationInfo";
import type { PathEntry } from "./PathEntry";
import type { ProviderDiagnostics } from "./ProviderDiagnostics";
import type { ProviderErrorRecord } from "./ProviderErrorRecord";

export type DiagnosticsReport = { generatedAt: number, appVersion: string, platform: string, backend: BackendStatus, database: DatabaseStatus, git: InstallationInfo, providers: Array<ProviderDiagnostics>, paths: Array<PathEntry>, providerErrors: Array<ProviderErrorRecord>, };
