// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentError } from "./AgentError";
import type { AgentWaiting } from "./AgentWaiting";
import type { CommandFinished } from "./CommandFinished";
import type { CommandOutput } from "./CommandOutput";
import type { CommandStarted } from "./CommandStarted";
import type { FileTouched } from "./FileTouched";
import type { GitBranchChanged } from "./GitBranchChanged";
import type { GitCommitCreated } from "./GitCommitCreated";
import type { GitStatusChanged } from "./GitStatusChanged";
import type { PermissionRequested } from "./PermissionRequested";
import type { PermissionResolved } from "./PermissionResolved";
import type { PromptSubmitted } from "./PromptSubmitted";
import type { ProviderErrorInfo } from "./ProviderErrorInfo";
import type { SessionEnded } from "./SessionEnded";
import type { SessionInfo } from "./SessionInfo";
import type { SubagentInfo } from "./SubagentInfo";
import type { TextNote } from "./TextNote";
import type { ToolFinished } from "./ToolFinished";
import type { ToolStarted } from "./ToolStarted";
import type { UsageSnapshot } from "./UsageSnapshot";

/**
 * Event type + payload. Serialized adjacently: `{"type": "tool.started", "payload": {...}}`.
 */
export type EventKind = { "type": "session.started", "payload": SessionInfo } | { "type": "session.updated", "payload": SessionInfo } | { "type": "session.ended", "payload": SessionEnded } | { "type": "prompt.submitted", "payload": PromptSubmitted } | { "type": "agent.thinking", "payload": TextNote } | { "type": "agent.message", "payload": TextNote } | { "type": "agent.idle", "payload": TextNote } | { "type": "agent.waiting", "payload": AgentWaiting } | { "type": "agent.error", "payload": AgentError } | { "type": "tool.started", "payload": ToolStarted } | { "type": "tool.completed", "payload": ToolFinished } | { "type": "tool.failed", "payload": ToolFinished } | { "type": "file.read", "payload": FileTouched } | { "type": "file.created", "payload": FileTouched } | { "type": "file.modified", "payload": FileTouched } | { "type": "file.deleted", "payload": FileTouched } | { "type": "command.started", "payload": CommandStarted } | { "type": "command.output", "payload": CommandOutput } | { "type": "command.completed", "payload": CommandFinished } | { "type": "command.failed", "payload": CommandFinished } | { "type": "permission.requested", "payload": PermissionRequested } | { "type": "permission.approved", "payload": PermissionResolved } | { "type": "permission.denied", "payload": PermissionResolved } | { "type": "subagent.started", "payload": SubagentInfo } | { "type": "subagent.updated", "payload": SubagentInfo } | { "type": "subagent.ended", "payload": SubagentInfo } | { "type": "git.branch_changed", "payload": GitBranchChanged } | { "type": "git.commit_created", "payload": GitCommitCreated } | { "type": "git.status_changed", "payload": GitStatusChanged } | { "type": "context.compacted", "payload": TextNote } | { "type": "usage.updated", "payload": UsageSnapshot } | { "type": "provider.error", "payload": ProviderErrorInfo };
