// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticsReport } from "./DiagnosticsReport";
import type { LogLine } from "./LogLine";
import type { ManagedProcessInfo } from "./ManagedProcessInfo";

/**
 * The file written by Diagnostics → "Export report".
 */
export type ExportedDiagnostics = { format: string, note: string, report: DiagnosticsReport, processes: Array<ManagedProcessInfo>, 
/**
 * Warnings and errors from the newest application and provider logs.
 */
recentWarnings: Array<LogLine>, };
