// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * A session discovered through an official listing command (e.g. `claude agents --json`).
 */
export type ExternalSessionInfo = { sessionId: SessionId, cwd?: string, pid?: number, title?: string, status?: string, startedAt?: number, };
