// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * One changed file (paths relative to the working tree, `/`-separated).
 */
export type FileChange = { path: string, 
/**
 * The previous path of a renamed or copied file.
 */
origPath?: string, 
/**
 * Change recorded in the index (will be in the next commit).
 */
staged?: ChangeKind, 
/**
 * Change in the working tree that is not staged yet.
 */
unstaged?: ChangeKind, };
