// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitStatusChanged = { dirty: number, staged: number, ahead?: number, behind?: number, };
