// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitStatusChanged = { 
/**
 * Files with changes that are not staged: edits, new files, conflicts.
 */
dirty: number, 
/**
 * Files with staged changes.
 */
staged: number, 
/**
 * Of `dirty`: new files Git does not track yet.
 */
untracked?: number, 
/**
 * Of `dirty`: files with merge conflicts.
 */
conflicted?: number, ahead?: number, behind?: number, };
