// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookEventCount } from "./HookEventCount";

export type HookBridgeStatus = { 
/**
 * Named pipe (Windows) or socket path (Unix) the relay connects to.
 */
endpoint: string, listening: boolean, error?: string, 
/**
 * Command written into hook configurations.
 */
relayCommand?: string, relayExists: boolean, 
/**
 * Hook events actually received, per provider — the empirical evidence
 * of what each CLI fires on this machine.
 */
events: Array<HookEventCount>, };
