// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this build of Agent Office has implemented for a provider.
 */
export type ImplementedFeatures = { detection: boolean, managedSessions: boolean, externalSessions: boolean, integrationSetup: boolean, };
