// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallationInfo = { installed: boolean, executablePath?: string, version?: string, 
/**
 * Raw first line printed by `--version` (for diagnostics).
 */
versionOutput?: string, error?: string, };
