// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationState } from "./IntegrationState";

export type IntegrationStatus = { state: IntegrationState, configPath?: string, details: Array<string>, };
