// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Integration buttons in Diagnostics.
 */
export type IntegrationAction = "status" | "install" | "repair" | "uninstall";
