// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";

export type LaunchRequest = { projectId?: ProjectId, 
/**
 * Working directory (project folder).
 */
cwd: string, model?: string, prompt?: string, name?: string, permissionMode?: string, };
