// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

export type LogLine = { 
/**
 * Timestamp as written (UTC, RFC 3339).
 */
at: string, level: LogLevel, target?: string, message: string, };
