// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";

export type LogTail = { 
/**
 * The file read (none yet: nothing was logged).
 */
file?: string, 
/**
 * Oldest first.
 */
lines: Array<LogLine>, 
/**
 * Older lines exist that are not shown.
 */
truncated: boolean, };
