// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A process Agent Office started (an agent CLI) and still tracks.
 */
export type ManagedProcessInfo = { pid: number, label: string, 
/**
 * The executable's file name.
 */
program: string, startedAt: number, running: boolean, 
/**
 * "running", or how it ended ("finished", "exited with code 2", …).
 */
status: string, exitCode?: number, lastOutputAt?: number, 
/**
 * Processes alive in its tree (the agent plus what it started).
 */
treeProcesses?: number, };
