// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewProject = { name: string, path: string, defaultProvider?: string, defaultModel?: string, defaultBranch?: string, };
