// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether desktop notifications can be shown here.
 */
export type NotificationSupport = { 
/**
 * Windows only.
 */
supported: boolean, 
/**
 * Run from a build folder: toasts appear as "Windows PowerShell".
 */
developmentBuild: boolean, };
