// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationPrefs = { enabled: boolean, 
/**
 * Only while Agent Office is not the active window.
 */
onlyInBackground: boolean, 
/**
 * An agent asks for permission.
 */
permission: boolean, 
/**
 * An agent waits for your answer.
 */
input: boolean, 
/**
 * An agent stopped with an error.
 */
errors: boolean, 
/**
 * A test run finished (passed or failed).
 */
tests: boolean, 
/**
 * An agent finished a long piece of work and waits for a new prompt.
 */
finished: boolean, 
/**
 * A session ended.
 */
sessionEnded: boolean, 
/**
 * Include the command, file or message (clipped, secrets already
 * redacted). Off: only who needs you and why.
 */
showDetails: boolean, };
