// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticeKind } from "./NoticeKind";

export type Notice = { kind: NoticeKind, title: string, body: string, 
/**
 * The agent to open when the notice is clicked.
 */
agentKey?: string, at: number, };
