// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Id of a pending permission request, unique within a session.
 */
export type PermissionRequestId = string;
