// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionRequestId } from "./PermissionRequestId";
import type { PermissionResolver } from "./PermissionResolver";

export type PermissionResolved = { requestId: PermissionRequestId, resolvedBy: PermissionResolver, message?: string, };
