// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who resolved a permission request.
 */
export type PermissionResolver = "app" | "provider" | "timeout" | "unknown";
