// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionDecision = { "decision": "approve", 
/**
 * Approve only this call (`false`) or for the rest of the session (`true`)
 * when the provider supports it.
 */
for_session: boolean, } | { "decision": "reject", message?: string, };
