// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionOption } from "./PermissionOption";
import type { PermissionRequestId } from "./PermissionRequestId";

export type PermissionRequested = { requestId: PermissionRequestId, toolName?: string, 
/**
 * What the agent wants to do ("Run: npm install").
 */
description: string, 
/**
 * True when Agent Office can answer this request (the UI shows Approve/Reject).
 */
canResolve: boolean, options: Array<PermissionOption>, };
