// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionOptionKind } from "./PermissionOptionKind";

export type PermissionOption = { 
/**
 * Provider's opaque option id (echoed back when answering).
 */
id: string, kind: PermissionOptionKind, label: string, };
