// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Preferences = { 
/**
 * Events older than this are deleted from the local database.
 */
retentionDays: number, 
/**
 * Maximum characters kept per string in stored events (tool output etc.).
 */
maxOutputChars: number, 
/**
 * Store prompt text. When off, only the fact that a prompt was sent is kept.
 */
storePrompts: boolean, 
/**
 * External sessions: permission requests wait for an answer in Agent
 * Office before Claude shows its own prompt. Off = observe only.
 */
answerPermissionsFromApp: boolean, 
/**
 * Seconds Agent Office waits for Approve/Reject.
 */
permissionTimeoutSecs: number, 
/**
 * Poll official listing commands (`claude agents --json`) for sessions.
 */
discoverExternalSessions: boolean, };
