// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, path: string, repositoryPath?: string, defaultProvider?: string, defaultModel?: string, defaultBranch?: string, 
/**
 * Free-form workspace settings (provider preferences, etc.).
 */
settings: Record<string, unknown>, createdAt: number, updatedAt: number, };
