// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project folder and the working tree it is in, if any.
 */
export type ProjectRepository = { projectId: string, worktreeRoot?: string, 
/**
 * Why there is none ("not a Git repository", a Git error, …).
 */
note?: string, };
