// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User preferences that apply to every provider (set in Agent Office).
 */
export type ProviderSettings = { 
/**
 * External sessions: let Agent Office answer permission prompts (the
 * agent's own prompt appears only after the timeout). Off = observe only.
 */
answerPermissionsFromApp: boolean, 
/**
 * Seconds Agent Office waits for Approve/Reject before handing the
 * decision back (external) or denying it (managed).
 */
permissionTimeoutSecs: number, 
/**
 * Discover external sessions through official listing commands.
 */
discoverExternalSessions: boolean, };
