// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * Static identity of a provider, used by the UI for names and colors.
 */
export type ProviderDescriptor = { id: ProviderId, displayName: string, 
/**
 * CSS color used to tint characters and badges.
 */
accentColor: string, 
/**
 * 1–3 characters shown on the character's badge. Never a trademarked logo.
 */
badge: string, 
/**
 * Executable names probed during detection (without extension).
 */
executableNames: Array<string>, homepage?: string, 
/**
 * True for the demo provider: its data is simulated.
 */
simulated: boolean, };
