// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationInfo } from "./InstallationInfo";
import type { IntegrationStatus } from "./IntegrationStatus";
import type { ProviderInfo } from "./ProviderInfo";

export type ProviderDiagnostics = { provider: ProviderInfo, installation: InstallationInfo, integration: IntegrationStatus, };
