// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Repository id (normalized repository root path).
 */
export type RepositoryId = string;
