// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a folder sits in Git: its working tree and the repository it
 * belongs to (a linked worktree shares the repository of its main one).
 */
export type RepoLocation = { 
/**
 * Top folder of the working tree the folder is in.
 */
worktreeRoot: string, 
/**
 * The repository: the main working tree's folder (shared by all its
 * worktrees). Used as the repository id.
 */
repositoryRoot: string, 
/**
 * True for a worktree added with `git worktree add`.
 */
linkedWorktree: boolean, };
