// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRepository } from "./ProjectRepository";
import type { RepositoryView } from "./RepositoryView";

export type RepositoriesReport = { 
/**
 * False when Git is not installed (then nothing else is filled).
 */
available: boolean, unavailableReason?: string, repositories: Array<RepositoryView>, projects: Array<ProjectRepository>, };
