// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitSession } from "./CommitSession";
import type { FileSessions } from "./FileSessions";
import type { RepoLocation } from "./RepoLocation";
import type { RepoSnapshot } from "./RepoSnapshot";

/**
 * Where the UI finds a repository's state.
 */
export type RepositoryView = { location: RepoLocation, snapshot?: RepoSnapshot, error?: string, refreshedAt?: number, 
/**
 * Sessions working in this tree (keys), active ones first.
 */
sessions: Array<string>, 
/**
 * Projects whose folder is in this tree (ids).
 */
projects: Array<string>, 
/**
 * Changed files an agent's tool is known to have written.
 */
fileSessions: Array<FileSessions>, 
/**
 * Commits credited to a session (see the module docs).
 */
commitSessions: Array<CommitSession>, };
