// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitInfo } from "./CommitInfo";
import type { RepoLocation } from "./RepoLocation";
import type { WorktreeInfo } from "./WorktreeInfo";
import type { WorktreeStatus } from "./WorktreeStatus";

/**
 * Everything shown for one working tree.
 */
export type RepoSnapshot = { location: RepoLocation, status: WorktreeStatus, 
/**
 * Latest commits of the checked-out branch, newest first.
 */
recentCommits: Array<CommitInfo>, 
/**
 * All worktrees of the repository (just the main one for most).
 */
worktrees: Array<WorktreeInfo>, };
