// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCategory } from "./ToolCategory";

export type RunningTool = { id?: string, name: string, category: ToolCategory, title?: string, startedAt: number, };
