// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionStats = { prompts: number, toolCalls: number, failedTools: number, commands: number, errors: number, subagents: number, commits: number, 
/**
 * Files the agent changed according to tool-level evidence (unique, capped).
 */
filesChanged: Array<string>, };
