// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";
import type { SessionId } from "./SessionId";
import type { SessionMode } from "./SessionMode";

export type SessionHandle = { provider: ProviderId, sessionId: SessionId, mode: SessionMode, pid?: number, };
