// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionMode } from "./SessionMode";

export type SessionInfo = { mode?: SessionMode, cwd?: string, model?: string, title?: string, reason?: string, permissionMode?: string, worktree?: string, pid?: number, };
