// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session id as reported by the provider (Claude `session_id`, Codex `threadId`, ACP `sessionId`).
 */
export type SessionId = string;
