// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File counts of a working tree.
 */
export type StatusCounts = { 
/**
 * Files with staged changes.
 */
staged: number, 
/**
 * Tracked files changed but not staged.
 */
unstaged: number, untracked: number, conflicted: number, };
