// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoreStats = { path?: string, schemaVersion: number, latestSchemaVersion: number, projects: number, sessions: number, events: number, sizeBytes: number, integrityOk: boolean, };
