// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubagentInfo = { 
/**
 * Subagent type/role ("Explore", "code-reviewer", …).
 */
agentType?: string, description?: string, reason?: string, };
