// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well a provider supports a capability.
 */
export type Support = "supported" | "partial" | "experimental" | "runtime" | "unsupported";
