// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallId } from "./ToolCallId";
import type { ToolCategory } from "./ToolCategory";

export type ToolFinished = { toolCallId?: ToolCallId, toolName: string, category: ToolCategory, durationMs?: number, 
/**
 * Output summary or error message (truncated).
 */
detail?: string, };
