// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-independent classification of a tool call.
 */
export type ToolCategory = "read" | "search" | "edit" | "execute" | "fetch" | "subagent" | "mcp" | "think" | "other";
