// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-scoped tool call id (Claude `tool_use_id`, Codex item id, ACP `toolCallId`).
 */
export type ToolCallId = string;
