// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallId } from "./ToolCallId";
import type { ToolCategory } from "./ToolCategory";

export type ToolStarted = { toolCallId?: ToolCallId, toolName: string, category: ToolCategory, 
/**
 * Short human-readable description ("Edit src/main.rs", "npm test").
 */
title?: string, };
