// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from "./AgentEvent";
import type { AgentState } from "./AgentState";
import type { SessionState } from "./SessionState";

export type UiBatch = { seq: number, sessions: Array<SessionState>, agents: Array<AgentState>, removedSessions: Array<string>, removedAgents: Array<string>, events: Array<AgentEvent>, 
/**
 * Events that happened but were not forwarded because of the cap.
 */
skippedEvents: number, };
