// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage and cost. Every field is optional: only values the provider
 * actually reported are filled in.
 */
export type UsageSnapshot = { inputTokens?: number, outputTokens?: number, cachedInputTokens?: number, reasoningTokens?: number, totalTokens?: number, contextWindow?: number, 
/**
 * Tokens currently in the context window (ACP `usage_update.used`).
 */
contextTokens?: number, costUsd?: number, 
/**
 * True when the cost is an estimate (e.g. Claude Code's client-side `total_cost_usd`).
 */
costIsEstimate: boolean, };
