// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";
import type { StatusCounts } from "./StatusCounts";

/**
 * `git status` of one working tree.
 */
export type WorktreeStatus = { 
/**
 * Checked-out branch (`None` when detached or unknown).
 */
branch?: string, detached: boolean, 
/**
 * Commit checked out (`None` in a repository without commits).
 */
head?: string, upstream?: string, 
/**
 * Commits not on the upstream yet / on the upstream but not here.
 * Only known when the branch has an upstream.
 */
ahead?: number, behind?: number, counts: StatusCounts, 
/**
 * Changed files (the first `MAX_FILES`; `counts` are always complete).
 */
files: Array<FileChange>, filesTruncated: boolean, };
