// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry of `git worktree list`.
 */
export type WorktreeInfo = { path: string, head?: string, branch?: string, detached: boolean, bare: boolean, locked: boolean, prunable: boolean, };
