// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentState } from "./AgentState";
import type { SessionState } from "./SessionState";

export type WorldSnapshot = { sessions: Array<SessionState>, agents: Array<AgentState>, };
